postgresql:
  image: sameersbn/postgresql:9.4-2
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
  volumes:
    - /srv/docker/redmine/postgresql:/var/lib/postgresql
    - /vagrant/redmine/backup:/shared
    - /srv/docker/redmine/backup:/shareddb
redmine:
  image: sameersbn/redmine:3.0.4
  links:
    - postgresql:postgresql
  environment:
    - TZ=Asia/Kolkata
    - REDMINE_PORT=10083
    - SMTP_ENABLED=false
    - SMTP_DOMAIN=www.example.com
    - SMTP_HOST=smtp.gmail.com
    - SMTP_PORT=587
    - SMTP_USER=mailer@example.com
    - SMTP_PASS=password
    - SMTP_STARTTLS=true
    - SMTP_AUTHENTICATION=:login
  ports:
    - "10083:80"
  volumes:
    - /srv/docker/redmine/redmine:/home/redmine/data
    - /srv/docker/redmine/lib:/home/redmine/redmine/lib
pgstudio:
  image: lukasmartinelli/pgstudio
  links:
    - postgresql:postgresql
  ports:
    - "8181:8080"
# redis:
#   image: redis
#   command: redis-server --appendonly yes
#   ports:
#     - "6379:6379"
#   volumes:
#     - /srv/docker/redis:/data
